-- Create the table for storing resume audits
create table audits (
  id bigint generated by default as identity primary key,
  user_id text not null, -- Stores the Clerk User ID
  file_name text,
  score integer,
  summary text,
  full_report jsonb, -- Stores the entire JSON result from the AI
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table audits enable row level security;

-- Create a policy that allows users to only see their own audits
create policy "Users can view their own audits"
  on audits for select
  using ( auth.uid()::text = user_id );

-- Create a policy that allows users to insert their own audits
-- Note: logic in our API handles the insertion securely, but RLS is good practice
create policy "Users can insert their own audits"
  on audits for insert
  with check ( auth.uid()::text = user_id );
